### ISSUE TITLE
链接报错 没搞懂

### ISSUE THREAD

**Issue by jiyahan** [luotan-123/libevent-server#4]
g++ -o ../bin/CenterServer  -L ../bin BaseCenterServer.o CenterServerManage.o CenterServerModule.o main.o jemalloc_cpp.o -lpthread -lKernel -lCommon -levent -ljemalloc -Wsign-compare
../bin/libCommon.so: undefined reference to `luaL_openlib'
../bin/libKernel.so: undefined reference to `bufferevent_getcb'
../bin/libKernel.so: undefined reference to `bufferevent_set_max_single_read'
../bin/libCommon.so: undefined reference to `event_enable_debug_logging'
../bin/libKernel.so: undefined reference to `bufferevent_get_max_single_read'
collect2: error: ld returned 1 exit status

是Makefile里面少链接动态库了吗 还是我编译有问题？Orz

**Comment by luotan-123** [comment]
1、设置动态(静态)库加载目录
vim /etc/ld.so.conf 
文件中加入一行 /usr/local/lib/
执行 root权限运行 ldconfig

2、生产core文件
启动coredumpshell.sh，重启系统生效。重启后，还需要以root执行以下命令。不执行core会生成在当前目录。
echo -e "/tmp/linuxserverplatform-corefile/core-%e-%p-%t" > /proc/sys/kernel/core_pattern
vim /etc/sysctl.conf  配置  net.ipv4.tcp_tw_recycle=1 让TIME-WAIT状态快速回收
sysctl -p立即生效

3、安装环境
如果之前已经安装过以下第三方库，就没必要安装
用到的轮子：
1、curl （centos下已经编译好库，不需要安装）
2、jemalloc （必须安装）
3、libevent（centos下已经编译好库，不需要安装）
4、libjson （centos下已经编译好库，不需要安装）
5、protobuf（必须安装）
6、redis （选择安装）
hiredis 已经编译成静态库。redis-server、redis-cli、redis-sentinel自己部署。
如果安装，由于redis依赖库hiredis、jemalloc、lua本服务器也用到。lua尽量用最新版安装，不要用redis自带的。hiredis最好安装。jemalloc可以选择redis自带或者最新版。
7、libmysqlclient（centos下已经编译好库，不需要安装）
8、lua  (需要下载安装，包括一些其它杂项，参考lua安装相关文档)
